Enable: true
Shop: true
Server:
  Gamemode: SURVIVAL
  Datafolder: folderHere
Hook:
  Residence: true
  WorldGuard: true
Price:
  Item: 10
  Fee: 200
  BuildDream: 500
  Redstone: 200
  BalanceMultiple: 1.0
Check:
  Barrier: true
  Bedrock: true
  Redstone: true